# Generated by Django 6.0.5 on 2026-05-27 13:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AppUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.TextField(unique=True)),
                ("password", models.TextField()),
                ("grade", models.IntegerField(blank=True, null=True)),
                ("efficient", models.IntegerField(blank=True, null=True)),
            ],
            options={
                "db_table": "users",
            },
        ),
        migrations.CreateModel(
            name="Location",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.TextField(blank=True, null=True)),
            ],
            options={
                "db_table": "locations",
            },
        ),
        migrations.CreateModel(
            name="FreeTime",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_of_time", models.DateField(blank=True, null=True)),
                ("start_time", models.TimeField()),
                ("end_time", models.TimeField()),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="cyber_security_app.appuser",
                    ),
                ),
                (
                    "location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="cyber_security_app.location",
                    ),
                ),
            ],
            options={
                "db_table": "free_times",
            },
        ),
        migrations.CreateModel(
            name="BookedTime",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="cyber_security_app.appuser",
                    ),
                ),
                (
                    "free_time",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="cyber_security_app.freetime",
                    ),
                ),
            ],
            options={
                "db_table": "booked_times",
            },
        ),
        migrations.AddField(
            model_name="appuser",
            name="booked_times",
            field=models.ManyToManyField(
                blank=True,
                related_name="booked_users",
                through="cyber_security_app.BookedTime",
                to="cyber_security_app.freetime",
            ),
        ),
        migrations.CreateModel(
            name="Message",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.TextField(blank=True, null=True)),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="cyber_security_app.appuser",
                    ),
                ),
            ],
            options={
                "db_table": "messages",
            },
        ),
        migrations.AddConstraint(
            model_name="bookedtime",
            constraint=models.UniqueConstraint(
                fields=("free_time", "user"), name="booked_times_pk"
            ),
        ),
        migrations.AddConstraint(
            model_name="appuser",
            constraint=models.CheckConstraint(
                condition=models.Q(("grade__gt", 3), ("grade__lt", 10)),
                name="check_grade",
            ),
        ),
        migrations.AddConstraint(
            model_name="appuser",
            constraint=models.CheckConstraint(
                condition=models.Q(("efficient__gt", 0), ("efficient__lt", 3)),
                name="efficient_check",
            ),
        ),
        migrations.AddConstraint(
            model_name="freetime",
            constraint=models.CheckConstraint(
                condition=models.Q(("start_time__lt", models.F("end_time"))),
                name="check_time",
            ),
        ),
    ]
