# Generated by Django 6.0.5 on 2026-05-27 13:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cyber_security_app", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("grade", models.IntegerField(blank=True, null=True)),
                ("efficient", models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveConstraint(
            model_name="appuser",
            name="check_grade",
        ),
        migrations.RemoveConstraint(
            model_name="appuser",
            name="efficient_check",
        ),
        migrations.AlterField(
            model_name="bookedtime",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterField(
            model_name="freetime",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterField(
            model_name="message",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="profile",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.RemoveField(
            model_name="appuser",
            name="booked_times",
        ),
        migrations.AddConstraint(
            model_name="userprofile",
            constraint=models.CheckConstraint(
                condition=models.Q(("grade__gt", 3), ("grade__lt", 10)),
                name="check_grade",
            ),
        ),
        migrations.AddConstraint(
            model_name="userprofile",
            constraint=models.CheckConstraint(
                condition=models.Q(("efficient__gt", 0), ("efficient__lt", 3)),
                name="efficient_check",
            ),
        ),
        migrations.DeleteModel(
            name="AppUser",
        ),
    ]
