# Generated by Django 6.0.6 on 2026-06-12 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cyber_security_app", "0002_userprofile_remove_appuser_check_grade_and_more"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="userprofile",
            name="check_grade",
        ),
        migrations.RemoveConstraint(
            model_name="userprofile",
            name="efficient_check",
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="efficient",
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="grade",
        ),
    ]
