# Generated by Django 6.0.5 on 2026-07-30 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0014_remove_user_booked_times"),
        ("cyber_security_app", "0003_remove_userprofile_check_grade_and_more"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="bookedtime",
            name="booked_times_pk",
        ),
        migrations.RemoveConstraint(
            model_name="freetime",
            name="check_time",
        ),
        migrations.RemoveField(
            model_name="bookedtime",
            name="free_time",
        ),
        migrations.RemoveField(
            model_name="bookedtime",
            name="user",
        ),
        migrations.RemoveField(
            model_name="freetime",
            name="location",
        ),
        migrations.RemoveField(
            model_name="freetime",
            name="user",
        ),
        migrations.DeleteModel(
            name="UserProfile",
        ),
        migrations.DeleteModel(
            name="BookedTime",
        ),
        migrations.DeleteModel(
            name="Location",
        ),
        migrations.DeleteModel(
            name="FreeTime",
        ),
    ]
